### ISSUE TITLE
Problems with multiple projectors

### ISSUE THREAD

**Issue by singerm** [Kinect/RoomAliveToolkit#20]
Hi guys,

we are using your framework with 2 projectors and 1 kinect.
The calibration works fine but when we try to start the sample or any other projection the second projector becomes black.
Both projectors are plugged in the same pc and placed verticaly with an slight overlap of the screens.
We've assigned one projector the index 1 and the second the index 2 (0 is the desktop).

Any clues what can be wrong?

**Comment by thundercarrot** [comment]
Can you zip up the calibration directory and put that somewhere where I can download it? I will take a look.

**Comment by singerm** [comment]
I've uploaded the zip to http://www.file-upload.net/download-11047788/kinectWithTwoCams.zip.html
Hopefully this will help!

**Comment by thundercarrot** [comment]
Sorry to take so long to get back to you. The problem is that the top projector was not calibrated successfully (run CalibrateEnsemble, select Projector 1 from the View menu-- you will see black, select Projector 0, and you see the bookshelf correctly). I believe the problem is that there is not quite enough stuff off the plane of the wall. The leading edge of the shelves is probably not enough. Try placing a box or two on the shelf and try calibrating again. Finally, once that works, you may need to think a bit about the FOV/aspect of the user view in the sample for this vertical configuration, but get the calibration working first. Good luck!

**Comment by devevderyadav** [comment]
Hi  @singerm  were u able to perceive the object in space (lets say at a height of 1-1.5 meter above the ground) rather  than near projected surface with 2 projectors and one kinect? 

Thanks & regards.
Devender

**Comment by singerm** [comment]
Sorry at the end we didn't use 2 projectors. We changed to one with a bigger projection screen than the kinect
