### ISSUE TITLE
Auto-save xml after Calibrate-Solve

### ISSUE THREAD

**Issue by rfilkov** [Kinect/RoomAliveToolkit#4]
Hello RoomAlive-team,
Your toolkit is great and has a good potential. What I'd ask is not really an issue, but a request. Please add 1-2 lines of code, so that when the 'Calibrate / Solve' gets invoked, the config-xml to be saved at the end of the calibration automatically. I usually forget it and leave the CalibrateEnsemble without saving the calibration config. Subsequent invocation of Calibrate / Solve causes a crash and then I have to start it all over again. Thank you in advance!

**Comment by thundercarrot** [comment]
Thanks for the feedback.

I think the crash after trying Solve again is because part of the acquisition process obtains camera calibration info from each Kinect. Solve presumes these to be there. I'm working in another branch ('develop') that adds a bit of error checking here and there.

As for saving, perhaps a safer and more standard approach would be to warn and offer to save when you quit the program if there are unsaved changes.

**Comment by rfilkov** [comment]
Thank you! I was also thinking about asking the user, if he wants to save the configuration before quitting the calibration-tool, but then I thought if there are really options at this point, apart from saving the config. If the user quits anyway, without saving the config-xml, maybe all the files generated by Solve should be deleted as well.

**Comment by thundercarrot** [comment]
I added a standard unsaved changes dialog box (see 'develop' branch).
